### ISSUE TITLE
Project build problem on Windows 

### ISSUE THREAD

**Issue by 0I0u3uk** [saksmt/ktest#70]
When I trying to build project on my windows pc, I see error 

> Illegal/unsupported escape sequence near index 7
 C:\vcs\github\ktest\doc
> 

Problem in this part of code
`def fullDocName = docFile.getAbsolutePath().replaceFirst(docDir.absolutePath, "")`

I fixed it localy so
`def fullDocName = docFile.getAbsolutePath().replaceFirst(docDir.absolutePath.replace("\\", "\\\\"), "")`

Can you fix it in repo?

**Comment by saksmt** [comment]
Fixed with #72  and #74
